export default {
  "login": "SarmadRehman",
  "id": 113442299,
  "node_id": "U_kgDOBsL9-w",
  "avatar_url": "https://avatars.githubusercontent.com/u/113442299?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/SarmadRehman",
  "html_url": "https://github.com/SarmadRehman",
  "followers_url": "https://api.github.com/users/SarmadRehman/followers",
  "following_url": "https://api.github.com/users/SarmadRehman/following{/other_user}",
  "gists_url": "https://api.github.com/users/SarmadRehman/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/SarmadRehman/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/SarmadRehman/subscriptions",
  "organizations_url": "https://api.github.com/users/SarmadRehman/orgs",
  "repos_url": "https://api.github.com/users/SarmadRehman/repos",
  "events_url": "https://api.github.com/users/SarmadRehman/events{/privacy}",
  "received_events_url": "https://api.github.com/users/SarmadRehman/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sarmad Rehman",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "I am an enthusiastic student of Software Engineering, aspirantly going through the hardwork of exploration of insights in this Soft-World.\r\n ",
  "twitter_username": null,
  "public_repos": 25,
  "public_gists": 0,
  "followers": 0,
  "following": 6,
  "created_at": "2022-09-13T12:33:59Z",
  "updated_at": "2023-08-19T22:10:56Z"
};